-- 다중 세션 지원을 위한 admin_user_session 테이블 구조 변경
-- 기존: admin_user_id가 PK (1인 1세션)
-- 변경: id 자동증가 PK + admin_user_id는 FK/인덱스 (1인 다중세션 가능)

-- 1. 기존 FK 제약 조건 삭제
ALTER TABLE admin_user_session DROP CONSTRAINT IF EXISTS fk_aus_user;

-- 2. 기존 PK 삭제
ALTER TABLE admin_user_session DROP CONSTRAINT IF EXISTS admin_user_session_pkey;

-- 3. id 자동증가 컬럼 추가
ALTER TABLE admin_user_session ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 4. id를 PK로 설정
ALTER TABLE admin_user_session ADD CONSTRAINT admin_user_session_pkey PRIMARY KEY (id);

-- 5. admin_user_id에 인덱스 추가 (NOT NULL 유지)
ALTER TABLE admin_user_session ALTER COLUMN admin_user_id SET NOT NULL;
ALTER TABLE admin_user_session ADD CONSTRAINT fk_aus_user FOREIGN KEY (admin_user_id) REFERENCES admin_user(seq_id);
CREATE INDEX idx_aus_admin_user_id ON admin_user_session(admin_user_id);

-- 6. access_token에 인덱스 추가 (토큰 기반 조회용)
CREATE INDEX idx_aus_access_token ON admin_user_session(access_token);
