-- V51: AuditableEntity 적용으로 누락된 created_at/updated_at 컬럼 추가

-- created_at 누락 테이블
ALTER TABLE aas_linkage ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE collected_data ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE admin_user_session ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE consent_history ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE login_attempts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE password_history ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE system_setting ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;

-- updated_at 누락 테이블
ALTER TABLE aas_element ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE aas_linkage ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE aas_shell ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE aas_submodel ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE collected_data ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE consent_history ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE dms_doc_file ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE login_attempts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE opcua_gateway_log ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE password_history ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE pii_audit_log ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE system_log ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;
