spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  cookie:
    secure: false

peakmate:
  opcua:
    simulation-mode: true

logging:
  level:
    com.peakmate: INFO
